# Generated by Django 4.2.6 on 2023-10-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ToDo', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], max_length=20)),
            ],
        ),
    ]
